In [ ]:
# Вспомогательные библиотеки и типизация
import os
from tqdm import tqdm
import warnings
import zipfile
from pathlib import Path
from datasets import load_dataset
from typing import List, Tuple, Set, Dict, Union, Callable, Any

# Для работы с данными
import pandas as pd
import numpy as np

# Для визуализации
import matplotlib.pyplot as plt
import seaborn as sns

# Интерпретация
import shap 

# Библиотека для сохранения модели
import joblib

# Ансамбли
import lightgbm as lgb
import xgboost as xgb
from catboost import CatBoostClassifier

# Метрики и модели
from sklearn.base import clone
from sklearn.calibration import calibration_curve
from sklearn.model_selection import StratifiedKFold, KFold, learning_curve, train_test_split
from sklearn.metrics import roc_curve, roc_auc_score, confusion_matrix, classification_report, precision_recall_curve, average_precision_score
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms

# Для автоматического подбора параметров моделей
import optuna
optuna.logging.set_verbosity(optuna.logging.WARNING)

from copy import deepcopy

# Настройка параметров библиотек
warnings.filterwarnings('ignore')
sns.set_theme(style="whitegrid", palette="muted")
plt.rcParams['figure.figsize'] = (12, 6)

# Для полного вывода без сокращения
# pd.set_option('display.max_columns', None)
# pd.set_option('display.max_rows', None)

RANDOM_STATE: int = 42
ROOT: Path = Path.cwd()
DATA_DIR: Path = ROOT / "data" if (ROOT / "data").exists() else ROOT

print("✅ Окружение настроено")

✅ Окружение настроено

In [2]:
print(f"Root: {ROOT}")

Root: /home/yamshchikov/ML_practice/Torchvision_core_project/MMAD

In [4]:
df_train: pd.DataFrame = pd.read_csv('train.csv')
df_train

,AAGE,ACLSWKR,ADTIND,ADTOCC,AHGA,AHRSPAY,AHSCOL,AMARITL,AMJIND,AMJOCC,...,PEFNTVTY,PEMNTVTY,PENATVTY,PRCITSHP,SEOTR,TAXINC,VETQVA,VETYN,WKSWORK,CLASS
0,43,LocalGovernment,43,10,Mastersdegree(MAMSMEngMEdMSWMBA),0,Not_in_universe,Married-civilianspousepresent,Education,Professionalspecialty,...,United-States,United-States,United-States,Native-BornintheUnitedStates,0,Not_in_universe,2,52,94,50000+
1,0,Not_in_universe,0,0,Children,0,Not_in_universe,Nevermarried,Not_in_universeorchildren,Not_in_universe,...,United-States,United-States,United-States,Native-BornintheUnitedStates,0,Not_in_universe,0,0,94,-50000
2,44,Private,11,22,Somecollegebutnodegree,0,Not_in_universe,Married-civilianspousepresent,Manufacturing-durablegoods,Admsupportincludingclerical,...,United-States,United-States,United-States,Native-BornintheUnitedStates,0,Not_in_universe,2,52,94,50000+
3,43,Self-employed-incorporated,35,17,Bachelorsdegree(BAABBS),0,Not_in_universe,Married-civilianspousepresent,Financeinsuranceandrealestate,Sales,...,United-States,United-States,United-States,Native-BornintheUnitedStates,0,Not_in_universe,2,52,94,50000+
4,39,Private,24,26,Bachelorsdegree(BAABBS),0,Not_in_universe,Married-civilianspousepresent,Manufacturing-nondurablegoods,Admsupportincludingclerical,...,United-States,United-States,United-States,Native-BornintheUnitedStates,0,Not_in_universe,2,52,94,50000+
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,57,Private,42,26,Somecollegebutnodegree,0,Not_in_universe,Married-civilianspousepresent,Medicalexcepthospital,Admsupportincludingclerical,...,United-States,El-Salvador,United-States,Native-BornintheUnitedStates,0,Not_in_universe,2,52,94,50000+
9996,13,Not_in_universe,0,0,Children,0,Not_in_universe,Nevermarried,Not_in_universeorchildren,Not_in_universe,...,United-States,United-States,United-States,Native-BornintheUnitedStates,0,Not_in_universe,0,0,94,-50000
9997,5,Not_in_universe,0,0,Children,0,Not_in_universe,Nevermarried,Not_in_universeorchildren,Not_in_universe,...,United-States,United-States,United-States,Native-BornintheUnitedStates,0,Not_in_universe,0,0,94,-50000
9998,64,Not_in_universe,0,0,10thgrade,0,Not_in_universe,Married-civilianspousepresent,Not_in_universeorchildren,Not_in_universe,...,United-States,United-States,United-States,Native-BornintheUnitedStates,0,Not_in_universe,2,0,94,-50000
9999,29,LocalGovernment,45,15,Mastersdegree(MAMSMEngMEdMSWMBA),0,Not_in_universe,Married-civilianspousepresent,Otherprofessionalservices,Techniciansandrelatedsupport,...,United-States,United-States,United-States,Native-BornintheUnitedStates,2,Not_in_universe,2,52,94,50000+

In [5]:
df_train.shape

(10000, 42)

In [13]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 42 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   AAGE      10000 non-null  int64
 1   ACLSWKR   10000 non-null  object
 2   ADTIND    10000 non-null  int64
 3   ADTOCC    10000 non-null  int64
 4   AHGA      10000 non-null  object
 5   AHRSPAY   10000 non-null  int64
 6   AHSCOL    10000 non-null  object
 7   AMARITL   10000 non-null  object
 8   AMJIND    10000 non-null  object
 9   AMJOCC    10000 non-null  object
 10  ARACE     10000 non-null  object
 11  AREORGN   10000 non-null  object
 12  ASEX      10000 non-null  object
 13  AUNMEM    10000 non-null  object
 14  AUNTYPE   10000 non-null  object
 15  AWKSTAT   10000 non-null  object
 16  CAPGAIN   10000 non-null  int64
 17  CAPLOSS   10000 non-null  int64
 18  DIVVAL    10000 non-null  int64
 19  FILESTAT  10000 non-null  object
 20  GRINREG   10000 non-null  object
 21  GRINST    10000 non-null  object
 22  HHDFMX    10000 non-null  object
 23  HHDREL    10000 non-null  object
 24  MARSUPWT  10000 non-null  float64
 25  MIGMTR1   10000 non-null  object
 26  MIGMTR3   10000 non-null  object
 27  MIGMTR4   10000 non-null  object
 28  MIGSAME   10000 non-null  object
 29  MIGSUN    10000 non-null  object
 30  NOEMP     10000 non-null  int64
 31  PARENT    10000 non-null  object
 32  PEFNTVTY  10000 non-null  object
 33  PEMNTVTY  10000 non-null  object
 34  PENATVTY  10000 non-null  object
 35  PRCITSHP  10000 non-null  object
 36  SEOTR     10000 non-null  int64
 37  TAXINC    10000 non-null  object
 38  VETQVA    10000 non-null  int64
 39  VETYN     10000 non-null  int64
 40  WKSWORK   10000 non-null  int64
 41  CLASS     10000 non-null  object
dtypes: float64(1), int64(12), object(29)
memory usage: 3.2+ MB

In [6]:
df_train.quantile

<bound method DataFrame.quantile of       AAGE                     ACLSWKR  ADTIND  ADTOCC  \
0       43             LocalGovernment      43      10
1        0             Not_in_universe       0       0
2       44                     Private      11      22
3       43  Self-employed-incorporated      35      17
4       39                     Private      24      26
...    ...                         ...     ...     ...
9995    57                     Private      42      26
9996    13             Not_in_universe       0       0
9997     5             Not_in_universe       0       0
9998    64             Not_in_universe       0       0
9999    29             LocalGovernment      45      15

                                  AHGA  AHRSPAY           AHSCOL  \
0     Mastersdegree(MAMSMEngMEdMSWMBA)        0  Not_in_universe
1                             Children        0  Not_in_universe
2               Somecollegebutnodegree        0  Not_in_universe
3              Bachelorsdegree(BAABBS)        0  Not_in_universe
4              Bachelorsdegree(BAABBS)        0  Not_in_universe
...                                ...      ...              ...
9995            Somecollegebutnodegree        0  Not_in_universe
9996                          Children        0  Not_in_universe
9997                          Children        0  Not_in_universe
9998                         10thgrade        0  Not_in_universe
9999  Mastersdegree(MAMSMEngMEdMSWMBA)        0  Not_in_universe

                            AMARITL                         AMJIND  \
0     Married-civilianspousepresent                      Education
1                      Nevermarried      Not_in_universeorchildren
2     Married-civilianspousepresent     Manufacturing-durablegoods
3     Married-civilianspousepresent  Financeinsuranceandrealestate
4     Married-civilianspousepresent  Manufacturing-nondurablegoods
...                             ...                            ...
9995  Married-civilianspousepresent          Medicalexcepthospital
9996                   Nevermarried      Not_in_universeorchildren
9997                   Nevermarried      Not_in_universeorchildren
9998  Married-civilianspousepresent      Not_in_universeorchildren
9999  Married-civilianspousepresent      Otherprofessionalservices

                            AMJOCC  ...       PEFNTVTY       PEMNTVTY  \
0            Professionalspecialty  ...  United-States  United-States
1                  Not_in_universe  ...  United-States  United-States
2      Admsupportincludingclerical  ...  United-States  United-States
3                            Sales  ...  United-States  United-States
4      Admsupportincludingclerical  ...  United-States  United-States
...                            ...  ...            ...            ...
9995   Admsupportincludingclerical  ...  United-States    El-Salvador
9996               Not_in_universe  ...  United-States  United-States
9997               Not_in_universe  ...  United-States  United-States
9998               Not_in_universe  ...  United-States  United-States
9999  Techniciansandrelatedsupport  ...  United-States  United-States

           PENATVTY                      PRCITSHP SEOTR           TAXINC  \
0     United-States  Native-BornintheUnitedStates     0  Not_in_universe
1     United-States  Native-BornintheUnitedStates     0  Not_in_universe
2     United-States  Native-BornintheUnitedStates     0  Not_in_universe
3     United-States  Native-BornintheUnitedStates     0  Not_in_universe
4     United-States  Native-BornintheUnitedStates     0  Not_in_universe
...             ...                           ...   ...              ...
9995  United-States  Native-BornintheUnitedStates     0  Not_in_universe
9996  United-States  Native-BornintheUnitedStates     0  Not_in_universe
9997  United-States  Native-BornintheUnitedStates     0  Not_in_universe
9998  United-States  Native-BornintheUnitedStates     0  Not_in_universe
9999  United-States  Native-BornintheUnitedStates     2  Not_in_universe

      VETQVA  VETYN  WKSWORK   CLASS
0          2     52       94  50000+
1          0      0       94  -50000
2          2     52       94  50000+
3          2     52       94  50000+
4          2     52       94  50000+
...      ...    ...      ...     ...
9995       2     52       94  50000+
9996       0      0       94  -50000
9997       0      0       94  -50000
9998       2      0       94  -50000
9999       2     52       94  50000+

[10000 rows x 42 columns]>

In [7]:
df_train.columns

Index(['AAGE', 'ACLSWKR', 'ADTIND', 'ADTOCC', 'AHGA', 'AHRSPAY', 'AHSCOL',
       'AMARITL', 'AMJIND', 'AMJOCC', 'ARACE', 'AREORGN', 'ASEX', 'AUNMEM',
       'AUNTYPE', 'AWKSTAT', 'CAPGAIN', 'CAPLOSS', 'DIVVAL', 'FILESTAT',
       'GRINREG', 'GRINST', 'HHDFMX', 'HHDREL', 'MARSUPWT', 'MIGMTR1',
       'MIGMTR3', 'MIGMTR4', 'MIGSAME', 'MIGSUN', 'NOEMP', 'PARENT',
       'PEFNTVTY', 'PEMNTVTY', 'PENATVTY', 'PRCITSHP', 'SEOTR', 'TAXINC',
       'VETQVA', 'VETYN', 'WKSWORK', 'CLASS'],
      dtype='object')

In [8]:
df_train.dtypes

AAGE          int64
ACLSWKR      object
ADTIND        int64
ADTOCC        int64
AHGA         object
AHRSPAY       int64
AHSCOL       object
AMARITL      object
AMJIND       object
AMJOCC       object
ARACE        object
AREORGN      object
ASEX         object
AUNMEM       object
AUNTYPE      object
AWKSTAT      object
CAPGAIN       int64
CAPLOSS       int64
DIVVAL        int64
FILESTAT     object
GRINREG      object
GRINST       object
HHDFMX       object
HHDREL       object
MARSUPWT    float64
MIGMTR1      object
MIGMTR3      object
MIGMTR4      object
MIGSAME      object
MIGSUN       object
NOEMP         int64
PARENT       object
PEFNTVTY     object
PEMNTVTY     object
PENATVTY     object
PRCITSHP     object
SEOTR         int64
TAXINC       object
VETQVA        int64
VETYN         int64
WKSWORK       int64
CLASS        object
dtype: object

In [9]:
df_train.index

RangeIndex(start=0, stop=10000, step=1)

In [10]:
df_train.axes

[RangeIndex(start=0, stop=10000, step=1),
 Index(['AAGE', 'ACLSWKR', 'ADTIND', 'ADTOCC', 'AHGA', 'AHRSPAY', 'AHSCOL',
        'AMARITL', 'AMJIND', 'AMJOCC', 'ARACE', 'AREORGN', 'ASEX', 'AUNMEM',
        'AUNTYPE', 'AWKSTAT', 'CAPGAIN', 'CAPLOSS', 'DIVVAL', 'FILESTAT',
        'GRINREG', 'GRINST', 'HHDFMX', 'HHDREL', 'MARSUPWT', 'MIGMTR1',
        'MIGMTR3', 'MIGMTR4', 'MIGSAME', 'MIGSUN', 'NOEMP', 'PARENT',
        'PEFNTVTY', 'PEMNTVTY', 'PENATVTY', 'PRCITSHP', 'SEOTR', 'TAXINC',
        'VETQVA', 'VETYN', 'WKSWORK', 'CLASS'],
       dtype='object')]

In [11]:
df_train[['VETYN','CLASS']]

      VETYN   CLASS
0        52  50000+
1         0  -50000
2        52  50000+
3        52  50000+
4        52  50000+
...     ...     ...
9995     52  50000+
9996      0  -50000
9997      0  -50000
9998      0  -50000
9999     52  50000+

[10000 rows x 2 columns]

In [14]:
print("Типы данных train:\n", df_train.dtypes)
print("Основные статистики для числовых признаков:\n", df_train.describe())

cat_cols_train = df_train.select_dtypes(include=['object']).columns
if len(cat_cols_train) > 0:
    print("Основные статистики для категориальных признаков:\n", df_train[cat_cols_train].describe())

Типы данных train:
 AAGE          int64
ACLSWKR      object
ADTIND        int64
ADTOCC        int64
AHGA         object
AHRSPAY       int64
AHSCOL       object
AMARITL      object
AMJIND       object
AMJOCC       object
ARACE        object
AREORGN      object
ASEX         object
AUNMEM       object
AUNTYPE      object
AWKSTAT      object
CAPGAIN       int64
CAPLOSS       int64
DIVVAL        int64
FILESTAT     object
GRINREG      object
GRINST       object
HHDFMX       object
HHDREL       object
MARSUPWT    float64
MIGMTR1      object
MIGMTR3      object
MIGMTR4      object
MIGSAME      object
MIGSUN       object
NOEMP         int64
PARENT       object
PEFNTVTY     object
PEMNTVTY     object
PENATVTY     object
PRCITSHP     object
SEOTR         int64
TAXINC       object
VETQVA        int64
VETYN         int64
WKSWORK       int64
CLASS        object
dtype: object
Основные статистики для числовых признаков:
                AAGE        ADTIND        ADTOCC       AHRSPAY       CAPGAIN  \
count  10000.000000  10000.000000  10000.000000  10000.000000  10000.000000
mean      39.635600     21.558200     11.907000     65.777000   2508.636400
std       18.917563     18.021928     13.504488    357.409484  12299.398762
min        0.000000      0.000000      0.000000      0.000000      0.000000
25%       29.000000      0.000000      0.000000      0.000000      0.000000
50%       40.000000     29.000000      5.000000      0.000000      0.000000
75%       51.000000     37.000000     23.000000      0.000000      0.000000
max       90.000000     51.000000     46.000000   9999.000000  99999.000000

            CAPLOSS        DIVVAL      MARSUPWT         NOEMP         SEOTR  \
count  10000.000000  10000.000000  10000.000000  10000.000000  10000.000000
mean     115.541200    806.283900   1748.875712      2.869600      0.210200
std      473.061487   4686.095191    952.250696      2.442129      0.590636
min        0.000000      0.000000    102.400000      0.000000      0.000000
25%        0.000000      0.000000   1094.127500      0.000000      0.000000
50%        0.000000      0.000000   1661.080000      3.000000      0.000000
75%        0.000000      5.000000   2174.292500      6.000000      0.000000
max     4356.000000  99999.000000  13145.100000      6.000000      2.000000

             VETQVA         VETYN  WKSWORK
count  10000.000000  10000.000000  10000.0
mean       1.732000     35.085000     94.0
std        0.670836     23.140366      0.0
min        0.000000      0.000000     94.0
25%        2.000000      0.000000     94.0
50%        2.000000     52.000000     94.0
75%        2.000000     52.000000     94.0
max        2.000000     52.000000     94.0
Основные статистики для категориальных признаков:
         ACLSWKR                AHGA           AHSCOL  \
count     10000               10000            10000
unique        9                  17                3
top     Private  Highschoolgraduate  Not_in_universe
freq       4742                2030             9650

                              AMARITL                     AMJIND  \
count                           10000                      10000
unique                              7                         24
top     Married-civilianspousepresent  Not_in_universeorchildren
freq                             5881                       2989

                 AMJOCC  ARACE   AREORGN   ASEX           AUNMEM  ...  \
count             10000  10000     10000  10000            10000  ...
unique               15      5         9      2                3  ...
top     Not_in_universe  White  Allother   Male  Not_in_universe  ...
freq               2989   8838      9115   6310             8652  ...

         MIGMTR4 MIGSAME           MIGSUN           PARENT       PEFNTVTY  \
count      10000   10000            10000            10000          10000
unique         9       3                3                5             40
top     Nonmover     Yes  Not_in_universe  Not_in_universe  United-States
freq        8609    8609             8688             8520           8527

             PEMNTVTY       PENATVTY                      PRCITSHP  \
count           10000          10000                         10000
unique             40             39                             5
top     United-States  United-States  Native-BornintheUnitedStates
freq             8589           9158                          9158

                 TAXINC   CLASS
count             10000   10000
unique                3       2
top     Not_in_universe  50000+
freq               9858    5000

[4 rows x 29 columns]

In [15]:
duplicates_train = df_train.duplicated(subset=['CLASS']).sum()
print(f"Количество дубликатов по 'CLASS' в train: {duplicates_train}")

Количество дубликатов по 'CLASS' в train: 9998

In [16]:
print(f"\nКолонки в train: {df_train.columns.tolist()}")
print(f"\nТипы данных:\n{df_train.dtypes.value_counts()}")

Колонки в train: ['AAGE', 'ACLSWKR', 'ADTIND', 'ADTOCC', 'AHGA', 'AHRSPAY', 'AHSCOL', 'AMARITL', 'AMJIND', 'AMJOCC', 'ARACE', 'AREORGN', 'ASEX', 'AUNMEM', 'AUNTYPE', 'AWKSTAT', 'CAPGAIN', 'CAPLOSS', 'DIVVAL', 'FILESTAT', 'GRINREG', 'GRINST', 'HHDFMX', 'HHDREL', 'MARSUPWT', 'MIGMTR1', 'MIGMTR3', 'MIGMTR4', 'MIGSAME', 'MIGSUN', 'NOEMP', 'PARENT', 'PEFNTVTY', 'PEMNTVTY', 'PENATVTY', 'PRCITSHP', 'SEOTR', 'TAXINC', 'VETQVA', 'VETYN', 'WKSWORK', 'CLASS']

Типы данных:
object     29
int64      12
float64     1
Name: count, dtype: int64

In [17]:
num_cols_train: pd.Index = df_train.select_dtypes(include=["int64", "float64"]).columns
cat_cols_train: pd.Index = df_train.select_dtypes(include=["object"]).columns

print(f"Числовые: {len(num_cols_train)}")
print(f"Категориальные: {len(cat_cols_train)}")

Числовые: 13
Категориальные: 29

In [18]:
float_train_cols: List[str] = df_train.select_dtypes(include=['float64']).columns.tolist()
float_train_cols

['MARSUPWT']

In [19]:
int_train_cols: List[str] = df_train.select_dtypes(include=['int64']).columns.tolist()
int_train_cols

['AAGE',
 'ADTIND',
 'ADTOCC',
 'AHRSPAY',
 'CAPGAIN',
 'CAPLOSS',
 'DIVVAL',
 'NOEMP',
 'SEOTR',
 'VETQVA',
 'VETYN',
 'WKSWORK']

In [20]:
object_train_cols: List[str] = df_train.select_dtypes(include=['object']).columns.tolist()
object_train_cols

['ACLSWKR',
 'AHGA',
 'AHSCOL',
 'AMARITL',
 'AMJIND',
 'AMJOCC',
 'ARACE',
 'AREORGN',
 'ASEX',
 'AUNMEM',
 'AUNTYPE',
 'AWKSTAT',
 'FILESTAT',
 'GRINREG',
 'GRINST',
 'HHDFMX',
 'HHDREL',
 'MIGMTR1',
 'MIGMTR3',
 'MIGMTR4',
 'MIGSAME',
 'MIGSUN',
 'PARENT',
 'PEFNTVTY',
 'PEMNTVTY',
 'PENATVTY',
 'PRCITSHP',
 'TAXINC',
 'CLASS']

In [29]:
df_train[(df_train['AHGA']=='Mastersdegree(MAMSMEngMEdMSWMBA)')&(df_train['AAGE']>30)].shape[0]/df_train[df_train['AAGE']>30].shape[0]

0.1210366694237662

In [30]:
df_train.iloc[4]
df_train['AAGE']
df_train[:3]

,AAGE,ACLSWKR,ADTIND,ADTOCC,AHGA,AHRSPAY,AHSCOL,AMARITL,AMJIND,AMJOCC,...,PEFNTVTY,PEMNTVTY,PENATVTY,PRCITSHP,SEOTR,TAXINC,VETQVA,VETYN,WKSWORK,CLASS
0,43,LocalGovernment,43,10,Mastersdegree(MAMSMEngMEdMSWMBA),0,Not_in_universe,Married-civilianspousepresent,Education,Professionalspecialty,...,United-States,United-States,United-States,Native-BornintheUnitedStates,0,Not_in_universe,2,52,94,50000+
1,0,Not_in_universe,0,0,Children,0,Not_in_universe,Nevermarried,Not_in_universeorchildren,Not_in_universe,...,United-States,United-States,United-States,Native-BornintheUnitedStates,0,Not_in_universe,0,0,94,-50000
2,44,Private,11,22,Somecollegebutnodegree,0,Not_in_universe,Married-civilianspousepresent,Manufacturing-durablegoods,Admsupportincludingclerical,...,United-States,United-States,United-States,Native-BornintheUnitedStates,0,Not_in_universe,2,52,94,50000+

In [31]:
df_train[df_train['AAGE']>30]

,AAGE,ACLSWKR,ADTIND,ADTOCC,AHGA,AHRSPAY,AHSCOL,AMARITL,AMJIND,AMJOCC,...,PEFNTVTY,PEMNTVTY,PENATVTY,PRCITSHP,SEOTR,TAXINC,VETQVA,VETYN,WKSWORK,CLASS
0,43,LocalGovernment,43,10,Mastersdegree(MAMSMEngMEdMSWMBA),0,Not_in_universe,Married-civilianspousepresent,Education,Professionalspecialty,...,United-States,United-States,United-States,Native-BornintheUnitedStates,0,Not_in_universe,2,52,94,50000+
2,44,Private,11,22,Somecollegebutnodegree,0,Not_in_universe,Married-civilianspousepresent,Manufacturing-durablegoods,Admsupportincludingclerical,...,United-States,United-States,United-States,Native-BornintheUnitedStates,0,Not_in_universe,2,52,94,50000+
3,43,Self-employed-incorporated,35,17,Bachelorsdegree(BAABBS),0,Not_in_universe,Married-civilianspousepresent,Financeinsuranceandrealestate,Sales,...,United-States,United-States,United-States,Native-BornintheUnitedStates,0,Not_in_universe,2,52,94,50000+
4,39,Private,24,26,Bachelorsdegree(BAABBS),0,Not_in_universe,Married-civilianspousepresent,Manufacturing-nondurablegoods,Admsupportincludingclerical,...,United-States,United-States,United-States,Native-BornintheUnitedStates,0,Not_in_universe,2,52,94,50000+
6,70,Not_in_universe,0,0,Highschoolgraduate,0,Not_in_universe,Married-civilianspousepresent,Not_in_universeorchildren,Not_in_universe,...,United-States,United-States,United-States,Native-BornintheUnitedStates,0,Not_in_universe,2,0,94,-50000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9992,90,Not_in_universe,0,0,Highschoolgraduate,0,Not_in_universe,Married-civilianspousepresent,Not_in_universeorchildren,Not_in_universe,...,United-States,United-States,United-States,Native-BornintheUnitedStates,0,Not_in_universe,2,26,94,50000+
9993,72,Not_in_universe,0,0,Highschoolgraduate,0,Not_in_universe,Nevermarried,Not_in_universeorchildren,Not_in_universe,...,Mexico,Mexico,United-States,Native-BornintheUnitedStates,0,Not_in_universe,2,0,94,-50000
9994,53,Private,33,19,7thand8thgrade,475,Not_in_universe,Married-civilianspousepresent,Retailtrade,Sales,...,United-States,United-States,United-States,Native-BornintheUnitedStates,0,Not_in_universe,2,52,94,-50000
9995,57,Private,42,26,Somecollegebutnodegree,0,Not_in_universe,Married-civilianspousepresent,Medicalexcepthospital,Admsupportincludingclerical,...,United-States,El-Salvador,United-States,Native-BornintheUnitedStates,0,Not_in_universe,2,52,94,50000+
9998,64,Not_in_universe,0,0,10thgrade,0,Not_in_universe,Married-civilianspousepresent,Not_in_universeorchildren,Not_in_universe,...,United-States,United-States,United-States,Native-BornintheUnitedStates,0,Not_in_universe,2,0,94,-50000

In [32]:
df_train['ACLSWKR'].value_counts()

ACLSWKR
Private                          4742
Not_in_universe                  2973
Self-employed-notIncorporated     699
LocalGovernment                   509
Self-employed-incorporated        491
StateGovernment                   298
FederalGovernment                 267
NeverWorked                        16
WithoutPay                          5
Name: count, dtype: int64

In [33]:
for name in df_train.columns:
    if df_train[name].dtype=='object':
        s=df_train[name].value_counts()
        if s[0]>int(0.8*df_train.index.size):
            print(name,' poor informativity ', s)
        if s[-1]<10:
            print(name,' small grads', s)
    else:
        if df_train[name].var()==0:
            print(name,'feature is constant')

ACLSWKR  small grads ACLSWKR
Private                          4742
Not_in_universe                  2973
Self-employed-notIncorporated     699
LocalGovernment                   509
Self-employed-incorporated        491
StateGovernment                   298
FederalGovernment                 267
NeverWorked                        16
WithoutPay                          5
Name: count, dtype: int64
AHSCOL  poor informativity  AHSCOL
Not_in_universe        9650
Highschool              176
Collegeoruniversity     174
Name: count, dtype: int64
AMJIND  small grads AMJIND
Not_in_universeorchildren          2989
Manufacturing-durablegoods          861
Retailtrade                         725
Financeinsuranceandrealestate       608
Education                           543
Manufacturing-nondurablegoods       513
Otherprofessionalservices           498
Businessandrepairservices           403
Construction                        379
Publicadministration                379
Medicalexcepthospital               346
Wholesaletrade                      306
Transportation                      301
Hospitalservices                    279
Agriculture                         158
Communications                      151
Utilitiesandsanitaryservices        130
PersonalservicesexceptprivateHH     109
Socialservices                      102
Entertainment                        92
Mining                               77
Privatehouseholdservices             27
Forestryandfisheries                 20
ArmedForces                           4
Name: count, dtype: int64
AMJOCC  small grads AMJOCC
Not_in_universe                      2989
Executiveadminandmanagerial          1668
Professionalspecialty                1664
Sales                                 919
Precisionproductioncraft&repair       641
Admsupportincludingclerical           594
Otherservice                          369
Machineoperatorsassmblrs&inspctrs     264
Transportationandmaterialmoving       247
Techniciansandrelatedsupport          195
Farmingforestryandfishing             148
Protectiveservices                    148
Handlersequipcleanersetc              130
Privatehouseholdservices               20
ArmedForces                             4
Name: count, dtype: int64
ARACE  poor informativity  ARACE
White                      8838
Black                       721
AsianorPacificIslander      266
Other                        97
AmerIndianAleutorEskimo      78
Name: count, dtype: int64
AREORGN  poor informativity  AREORGN
Allother                  9115
Mexican-American           295
Mexican(Mexicano)          205
CentralorSouthAmerican     111
PuertoRican                103
OtherSpanish                81
Cuban                       58
Donotknow                   18
Chicano                     14
Name: count, dtype: int64
AUNMEM  poor informativity  AUNMEM
Not_in_universe    8652
No                 1127
Yes                 221
Name: count, dtype: int64
AUNTYPE  poor informativity  AUNTYPE
Not_in_universe      9762
Otherjobloser         107
Re-entrant             73
Jobloser-onlayoff      27
Newentrant             16
Jobleaver              15
Name: count, dtype: int64
AWKSTAT  poor informativity  AWKSTAT
ChildrenorArmedForces    10000
Name: count, dtype: int64
GRINREG  poor informativity  GRINREG
Not_in_universe    8688
South               398
West                355
Midwest             292
Northeast           239
Abroad               28
Name: count, dtype: int64
GRINST  poor informativity  GRINST
Not_in_universe       8688
California             145
NorthCarolina           95
Utah                    89
Florida                 82
Minnesota               63
Oklahoma                54
NewMexico               51
Michigan                40
Abroad                  37
Indiana                 35
NorthDakota             34
Alaska                  31
NewHampshire            29
Kentucky                22
Texas                   21
Oregon                  20
Louisiana               20
Arizona                 20
NewYork                 20
Colorado                20
Wyoming                 20
DistrictofColumbia      19
WestVirginia            19
Montana                 17
Illinois                17
Vermont                 16
Tennessee               16
Alabama                 16
Ohio                    16
Pennsylvania            16
Maine                   16
Connecticut             15
Massachusetts           15
Missouri                14
Arkansas                14
Mississippi             13
Nevada                  13
Georgia                 13
Iowa                    12
Nebraska                12
Maryland                12
SouthDakota             12
Kansas                  11
NewJersey               10
SouthCarolina            9
Wisconsin                8
Virginia                 7
Delaware                 5
Idaho                    1
Name: count, dtype: int64
GRINST  small grads GRINST
Not_in_universe       8688
California             145
NorthCarolina           95
Utah                    89
Florida                 82
Minnesota               63
Oklahoma                54
NewMexico               51
Michigan                40
Abroad                  37
Indiana                 35
NorthDakota             34
Alaska                  31
NewHampshire            29
Kentucky                22
Texas                   21
Oregon                  20
Louisiana               20
Arizona                 20
NewYork                 20
Colorado                20
Wyoming                 20
DistrictofColumbia      19
WestVirginia            19
Montana                 17
Illinois                17
Vermont                 16
Tennessee               16
Alabama                 16
Ohio                    16
Pennsylvania            16
Maine                   16
Connecticut             15
Massachusetts           15
Missouri                14
Arkansas                14
Mississippi             13
Nevada                  13
Georgia                 13
Iowa                    12
Nebraska                12
Maryland                12
SouthDakota             12
Kansas                  11
NewJersey               10
SouthCarolina            9
Wisconsin                8
Virginia                 7
Delaware                 5
Idaho                    1
Name: count, dtype: int64
HHDFMX  small grads HHDFMX
Householder                                 4535
Spouseofhouseholder                         1858
Child<18nevermarrnotinsubfamily             1357
Nonfamilyhouseholder                        1261
Child18+nevermarrNotinasubfamily             380
Secondaryindividual                          214
OtherRel18+evermarrnotinsubfamily             56
OtherRel18+nevermarrnotinsubfamily            46
Grandchild<18nevermarrchildofsubfamilyRP      44
Child18+evermarrNotinasubfamily               37
RPofunrelatedsubfamily                        25
Grandchild<18nevermarrnotinsubfamily          23
Child18+evermarrRPofsubfamily                 22
Childunder18ofRPofunrelsubfamily              20
OtherRel<18nevermarrchildofsubfamilyRP        20
OtherRel18+spouseofsubfamilyRP                19
OtherRel18+evermarrRPofsubfamily              19
Child18+nevermarrRPofsubfamily                18
OtherRel<18nevermarrnotinsubfamily            13
Grandchild18+nevermarrnotinsubfamily          12
Ingroupquarters                                7
SpouseofRPofunrelatedsubfamily                 6
Child18+spouseofsubfamilyRP                    4
OtherRel18+nevermarrRPofsubfamily              3
Grandchild<18evermarrnotinsubfamily            1
Name: count, dtype: int64
HHDREL  small grads HHDREL
Householder                          5796
Spouseofhouseholder                  1859
Childunder18nevermarried             1359
Child18orolder                        461
Nonrelativeofhouseholder              265
Otherrelativeofhouseholder            256
GroupQuarters-Secondaryindividual       4
Name: count, dtype: int64
MIGMTR1  poor informativity  MIGMTR1
Nonmover           8609
MSAtoMSA            945
NonMSAtononMSA      193
Not_in_universe      79
MSAtononMSA          60
NonMSAtoMSA          52
Notidentifiable      34
AbroadtoMSA          23
AbroadtononMSA        5
Name: count, dtype: int64
MIGMTR1  small grads MIGMTR1
Nonmover           8609
MSAtoMSA            945
NonMSAtononMSA      193
Not_in_universe      79
MSAtononMSA          60
NonMSAtoMSA          52
Notidentifiable      34
AbroadtoMSA          23
AbroadtononMSA        5
Name: count, dtype: int64
MIGMTR3  poor informativity  MIGMTR3
Nonmover                       8609
Samecounty                      812
Differentcountysamestate        232
Differentregion                 116
Not_in_universe                  79
Differentstatesamedivision       69
Differentdivisionsameregion      55
Abroad                           28
Name: count, dtype: int64
MIGMTR4  poor informativity  MIGMTR4
Nonmover                     8609
Samecounty                    812
Differentcountysamestate      232
DifferentstateinSouth          84
Not_in_universe                79
DifferentstateinWest           69
DifferentstateinMidwest        49
DifferentstateinNortheast      38
Abroad                         28
Name: count, dtype: int64
MIGSAME  poor informativity  MIGSAME
Yes                             8609
No                              1312
Not_in_universeunder1yearold      79
Name: count, dtype: int64
MIGSUN  poor informativity  MIGSUN
Not_in_universe    8688
No                  823
Yes                 489
Name: count, dtype: int64
PARENT  poor informativity  PARENT
Not_in_universe         8520
Bothparentspresent      1031
Motheronlypresent        377
Neitherparentpresent      37
Fatheronlypresent         35
Name: count, dtype: int64
PEFNTVTY  poor informativity  PEFNTVTY
United-States               8527
Mexico                       291
Italy                        120
Canada                        92
Puerto-Rico                   89
Germany                       82
Poland                        64
Philippines                   60
Cuba                          56
England                       54
China                         49
Ireland                       44
India                         44
Dominican-Republic            41
El-Salvador                   39
SouthKorea                    31
Greece                        30
Hungary                       27
Taiwan                        22
Japan                         20
Nicaragua                     19
Ecuador                       18
Guatemala                     17
Portugal                      16
Peru                          15
Jamaica                       15
Columbia                      15
Scotland                      15
Vietnam                       13
France                        13
Iran                          11
Haiti                         11
Yugoslavia                    10
Thailand                       7
Laos                           6
Honduras                       6
Cambodia                       4
Outlying-US(GuamUSVIetc)       3
HongKong                       2
Trinadad&Tobago                2
Name: count, dtype: int64
PEFNTVTY  small grads PEFNTVTY
United-States               8527
Mexico                       291
Italy                        120
Canada                        92
Puerto-Rico                   89
Germany                       82
Poland                        64
Philippines                   60
Cuba                          56
England                       54
China                         49
Ireland                       44
India                         44
Dominican-Republic            41
El-Salvador                   39
SouthKorea                    31
Greece                        30
Hungary                       27
Taiwan                        22
Japan                         20
Nicaragua                     19
Ecuador                       18
Guatemala                     17
Portugal                      16
Peru                          15
Jamaica                       15
Columbia                      15
Scotland                      15
Vietnam                       13
France                        13
Iran                          11
Haiti                         11
Yugoslavia                    10
Thailand                       7
Laos                           6
Honduras                       6
Cambodia                       4
Outlying-US(GuamUSVIetc)       3
HongKong                       2
Trinadad&Tobago                2
Name: count, dtype: int64
PEMNTVTY  poor informativity  PEMNTVTY
United-States               8589
Mexico                       297
Germany                       91
Canada                        89
Puerto-Rico                   82
Italy                         74
Philippines                   60
England                       57
Poland                        55
Cuba                          53
El-Salvador                   50
Ireland                       50
India                         44
China                         43
Dominican-Republic            30
SouthKorea                    30
Japan                         25
Hungary                       23
Taiwan                        23
Greece                        20
Columbia                      19
Nicaragua                     17
Ecuador                       17
France                        17
Jamaica                       15
Peru                          14
Scotland                      14
Guatemala                     13
Vietnam                       13
Haiti                         12
Portugal                      12
Yugoslavia                    11
Iran                          11
Honduras                       8
Thailand                       7
Laos                           6
HongKong                       3
Cambodia                       3
Outlying-US(GuamUSVIetc)       2
Trinadad&Tobago                1
Name: count, dtype: int64
PEMNTVTY  small grads PEMNTVTY
United-States               8589
Mexico                       297
Germany                       91
Canada                        89
Puerto-Rico                   82
Italy                         74
Philippines                   60
England                       57
Poland                        55
Cuba                          53
El-Salvador                   50
Ireland                       50
India                         44
China                         43
Dominican-Republic            30
SouthKorea                    30
Japan                         25
Hungary                       23
Taiwan                        23
Greece                        20
Columbia                      19
Nicaragua                     17
Ecuador                       17
France                        17
Jamaica                       15
Peru                          14
Scotland                      14
Guatemala                     13
Vietnam                       13
Haiti                         12
Portugal                      12
Yugoslavia                    11
Iran                          11
Honduras                       8
Thailand                       7
Laos                           6
HongKong                       3
Cambodia                       3
Outlying-US(GuamUSVIetc)       2
Trinadad&Tobago                1
Name: count, dtype: int64
PENATVTY  poor informativity  PENATVTY
United-States         9158
Mexico                 168
Germany                 56
Philippines             49
Puerto-Rico             43
Canada                  42
Cuba                    42
India                   38
England                 31
El-Salvador             30
SouthKorea              30
China                   23
Taiwan                  22
Dominican-Republic      22
Italy                   20
Japan                   19
Poland                  18
Greece                  16
Jamaica                 14
Peru                    14
Columbia                14
Vietnam                 14
Nicaragua               12
Guatemala               12
Iran                    11
Ecuador                 10
Portugal                 9
Haiti                    9
Ireland                  9
France                   9
Thailand                 8
Honduras                 7
Scotland                 5
Hungary                  4
Laos                     4
HongKong                 3
Cambodia                 2
Yugoslavia               2
Trinadad&Tobago          1
Name: count, dtype: int64
PENATVTY  small grads PENATVTY
United-States         9158
Mexico                 168
Germany                 56
Philippines             49
Puerto-Rico             43
Canada                  42
Cuba                    42
India                   38
England                 31
El-Salvador             30
SouthKorea              30
China                   23
Taiwan                  22
Dominican-Republic      22
Italy                   20
Japan                   19
Poland                  18
Greece                  16
Jamaica                 14
Peru                    14
Columbia                14
Vietnam                 14
Nicaragua               12
Guatemala               12
Iran                    11
Ecuador                 10
Portugal                 9
Haiti                    9
Ireland                  9
France                   9
Thailand                 8
Honduras                 7
Scotland                 5
Hungary                  4
Laos                     4
HongKong                 3
Cambodia                 2
Yugoslavia               2
Trinadad&Tobago          1
Name: count, dtype: int64
PRCITSHP  poor informativity  PRCITSHP
Native-BornintheUnitedStates             9158
Foreignborn-NotacitizenofUS               429
Foreignborn-UScitizenbynaturalization     298
Native-BornabroadofAmericanParent(s)       72
Native-BorninPuertoRicoorUSOutlying        43
Name: count, dtype: int64
TAXINC  poor informativity  TAXINC
Not_in_universe    9858
No                  126
Yes                  16
Name: count, dtype: int64
WKSWORK feature is constant

/tmp/ipykernel_1426323/3478013104.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[0]>int(0.8*df_train.index.size):
/tmp/ipykernel_1426323/3478013104.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[-1]<10:
/tmp/ipykernel_1426323/3478013104.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[0]>int(0.8*df_train.index.size):
/tmp/ipykernel_1426323/3478013104.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[-1]<10:
/tmp/ipykernel_1426323/3478013104.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[0]>int(0.8*df_train.index.size):
/tmp/ipykernel_1426323/3478013104.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[-1]<10:
/tmp/ipykernel_1426323/3478013104.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[0]>int(0.8*df_train.index.size):
/tmp/ipykernel_1426323/3478013104.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[-1]<10:
/tmp/ipykernel_1426323/3478013104.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[0]>int(0.8*df_train.index.size):
/tmp/ipykernel_1426323/3478013104.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[-1]<10:
/tmp/ipykernel_1426323/3478013104.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[0]>int(0.8*df_train.index.size):
/tmp/ipykernel_1426323/3478013104.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[-1]<10:
/tmp/ipykernel_1426323/3478013104.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[0]>int(0.8*df_train.index.size):
/tmp/ipykernel_1426323/3478013104.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[-1]<10:
/tmp/ipykernel_1426323/3478013104.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[0]>int(0.8*df_train.index.size):
/tmp/ipykernel_1426323/3478013104.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[-1]<10:
/tmp/ipykernel_1426323/3478013104.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[0]>int(0.8*df_train.index.size):
/tmp/ipykernel_1426323/3478013104.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[-1]<10:
/tmp/ipykernel_1426323/3478013104.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[0]>int(0.8*df_train.index.size):
/tmp/ipykernel_1426323/3478013104.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[-1]<10:
/tmp/ipykernel_1426323/3478013104.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[0]>int(0.8*df_train.index.size):
/tmp/ipykernel_1426323/3478013104.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[-1]<10:
/tmp/ipykernel_1426323/3478013104.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[0]>int(0.8*df_train.index.size):
/tmp/ipykernel_1426323/3478013104.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[-1]<10:
/tmp/ipykernel_1426323/3478013104.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[0]>int(0.8*df_train.index.size):
/tmp/ipykernel_1426323/3478013104.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[-1]<10:
/tmp/ipykernel_1426323/3478013104.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[0]>int(0.8*df_train.index.size):
/tmp/ipykernel_1426323/3478013104.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[-1]<10:
/tmp/ipykernel_1426323/3478013104.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[0]>int(0.8*df_train.index.size):
/tmp/ipykernel_1426323/3478013104.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[-1]<10:
/tmp/ipykernel_1426323/3478013104.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[0]>int(0.8*df_train.index.size):
/tmp/ipykernel_1426323/3478013104.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[-1]<10:
/tmp/ipykernel_1426323/3478013104.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[0]>int(0.8*df_train.index.size):
/tmp/ipykernel_1426323/3478013104.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[-1]<10:
/tmp/ipykernel_1426323/3478013104.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[0]>int(0.8*df_train.index.size):
/tmp/ipykernel_1426323/3478013104.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[-1]<10:
/tmp/ipykernel_1426323/3478013104.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[0]>int(0.8*df_train.index.size):
/tmp/ipykernel_1426323/3478013104.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[-1]<10:
/tmp/ipykernel_1426323/3478013104.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[0]>int(0.8*df_train.index.size):
/tmp/ipykernel_1426323/3478013104.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[-1]<10:
/tmp/ipykernel_1426323/3478013104.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[0]>int(0.8*df_train.index.size):
/tmp/ipykernel_1426323/3478013104.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[-1]<10:
/tmp/ipykernel_1426323/3478013104.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[0]>int(0.8*df_train.index.size):
/tmp/ipykernel_1426323/3478013104.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[-1]<10:
/tmp/ipykernel_1426323/3478013104.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[0]>int(0.8*df_train.index.size):
/tmp/ipykernel_1426323/3478013104.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[-1]<10:
/tmp/ipykernel_1426323/3478013104.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[0]>int(0.8*df_train.index.size):
/tmp/ipykernel_1426323/3478013104.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[-1]<10:
/tmp/ipykernel_1426323/3478013104.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[0]>int(0.8*df_train.index.size):
/tmp/ipykernel_1426323/3478013104.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[-1]<10:
/tmp/ipykernel_1426323/3478013104.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[0]>int(0.8*df_train.index.size):
/tmp/ipykernel_1426323/3478013104.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[-1]<10:
/tmp/ipykernel_1426323/3478013104.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[0]>int(0.8*df_train.index.size):
/tmp/ipykernel_1426323/3478013104.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[-1]<10:
/tmp/ipykernel_1426323/3478013104.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[0]>int(0.8*df_train.index.size):
/tmp/ipykernel_1426323/3478013104.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[-1]<10:
/tmp/ipykernel_1426323/3478013104.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[0]>int(0.8*df_train.index.size):
/tmp/ipykernel_1426323/3478013104.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if s[-1]<10:

In [34]:
df_train.replace(to_replace={'AMARITL': {'Separated': 'Otherwise','Widowed': 'Otherwise','Divorsed':'Otherwise'}})

,AAGE,ACLSWKR,ADTIND,ADTOCC,AHGA,AHRSPAY,AHSCOL,AMARITL,AMJIND,AMJOCC,...,PEFNTVTY,PEMNTVTY,PENATVTY,PRCITSHP,SEOTR,TAXINC,VETQVA,VETYN,WKSWORK,CLASS
0,43,LocalGovernment,43,10,Mastersdegree(MAMSMEngMEdMSWMBA),0,Not_in_universe,Married-civilianspousepresent,Education,Professionalspecialty,...,United-States,United-States,United-States,Native-BornintheUnitedStates,0,Not_in_universe,2,52,94,50000+
1,0,Not_in_universe,0,0,Children,0,Not_in_universe,Nevermarried,Not_in_universeorchildren,Not_in_universe,...,United-States,United-States,United-States,Native-BornintheUnitedStates,0,Not_in_universe,0,0,94,-50000
2,44,Private,11,22,Somecollegebutnodegree,0,Not_in_universe,Married-civilianspousepresent,Manufacturing-durablegoods,Admsupportincludingclerical,...,United-States,United-States,United-States,Native-BornintheUnitedStates,0,Not_in_universe,2,52,94,50000+
3,43,Self-employed-incorporated,35,17,Bachelorsdegree(BAABBS),0,Not_in_universe,Married-civilianspousepresent,Financeinsuranceandrealestate,Sales,...,United-States,United-States,United-States,Native-BornintheUnitedStates,0,Not_in_universe,2,52,94,50000+
4,39,Private,24,26,Bachelorsdegree(BAABBS),0,Not_in_universe,Married-civilianspousepresent,Manufacturing-nondurablegoods,Admsupportincludingclerical,...,United-States,United-States,United-States,Native-BornintheUnitedStates,0,Not_in_universe,2,52,94,50000+
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,57,Private,42,26,Somecollegebutnodegree,0,Not_in_universe,Married-civilianspousepresent,Medicalexcepthospital,Admsupportincludingclerical,...,United-States,El-Salvador,United-States,Native-BornintheUnitedStates,0,Not_in_universe,2,52,94,50000+
9996,13,Not_in_universe,0,0,Children,0,Not_in_universe,Nevermarried,Not_in_universeorchildren,Not_in_universe,...,United-States,United-States,United-States,Native-BornintheUnitedStates,0,Not_in_universe,0,0,94,-50000
9997,5,Not_in_universe,0,0,Children,0,Not_in_universe,Nevermarried,Not_in_universeorchildren,Not_in_universe,...,United-States,United-States,United-States,Native-BornintheUnitedStates,0,Not_in_universe,0,0,94,-50000
9998,64,Not_in_universe,0,0,10thgrade,0,Not_in_universe,Married-civilianspousepresent,Not_in_universeorchildren,Not_in_universe,...,United-States,United-States,United-States,Native-BornintheUnitedStates,0,Not_in_universe,2,0,94,-50000
9999,29,LocalGovernment,45,15,Mastersdegree(MAMSMEngMEdMSWMBA),0,Not_in_universe,Married-civilianspousepresent,Otherprofessionalservices,Techniciansandrelatedsupport,...,United-States,United-States,United-States,Native-BornintheUnitedStates,2,Not_in_universe,2,52,94,50000+

In [35]:
df_train.loc[df_train['AMARITL']!='Married-civilianspousepresent','AMARITL']='Otherwise'
df_train

,AAGE,ACLSWKR,ADTIND,ADTOCC,AHGA,AHRSPAY,AHSCOL,AMARITL,AMJIND,AMJOCC,...,PEFNTVTY,PEMNTVTY,PENATVTY,PRCITSHP,SEOTR,TAXINC,VETQVA,VETYN,WKSWORK,CLASS
0,43,LocalGovernment,43,10,Mastersdegree(MAMSMEngMEdMSWMBA),0,Not_in_universe,Married-civilianspousepresent,Education,Professionalspecialty,...,United-States,United-States,United-States,Native-BornintheUnitedStates,0,Not_in_universe,2,52,94,50000+
1,0,Not_in_universe,0,0,Children,0,Not_in_universe,Otherwise,Not_in_universeorchildren,Not_in_universe,...,United-States,United-States,United-States,Native-BornintheUnitedStates,0,Not_in_universe,0,0,94,-50000
2,44,Private,11,22,Somecollegebutnodegree,0,Not_in_universe,Married-civilianspousepresent,Manufacturing-durablegoods,Admsupportincludingclerical,...,United-States,United-States,United-States,Native-BornintheUnitedStates,0,Not_in_universe,2,52,94,50000+
3,43,Self-employed-incorporated,35,17,Bachelorsdegree(BAABBS),0,Not_in_universe,Married-civilianspousepresent,Financeinsuranceandrealestate,Sales,...,United-States,United-States,United-States,Native-BornintheUnitedStates,0,Not_in_universe,2,52,94,50000+
4,39,Private,24,26,Bachelorsdegree(BAABBS),0,Not_in_universe,Married-civilianspousepresent,Manufacturing-nondurablegoods,Admsupportincludingclerical,...,United-States,United-States,United-States,Native-BornintheUnitedStates,0,Not_in_universe,2,52,94,50000+
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,57,Private,42,26,Somecollegebutnodegree,0,Not_in_universe,Married-civilianspousepresent,Medicalexcepthospital,Admsupportincludingclerical,...,United-States,El-Salvador,United-States,Native-BornintheUnitedStates,0,Not_in_universe,2,52,94,50000+
9996,13,Not_in_universe,0,0,Children,0,Not_in_universe,Otherwise,Not_in_universeorchildren,Not_in_universe,...,United-States,United-States,United-States,Native-BornintheUnitedStates,0,Not_in_universe,0,0,94,-50000
9997,5,Not_in_universe,0,0,Children,0,Not_in_universe,Otherwise,Not_in_universeorchildren,Not_in_universe,...,United-States,United-States,United-States,Native-BornintheUnitedStates,0,Not_in_universe,0,0,94,-50000
9998,64,Not_in_universe,0,0,10thgrade,0,Not_in_universe,Married-civilianspousepresent,Not_in_universeorchildren,Not_in_universe,...,United-States,United-States,United-States,Native-BornintheUnitedStates,0,Not_in_universe,2,0,94,-50000
9999,29,LocalGovernment,45,15,Mastersdegree(MAMSMEngMEdMSWMBA),0,Not_in_universe,Married-civilianspousepresent,Otherprofessionalservices,Techniciansandrelatedsupport,...,United-States,United-States,United-States,Native-BornintheUnitedStates,2,Not_in_universe,2,52,94,50000+

In [36]:
# 1. Заменяем значения сразу на числа (1 и 0), а не на строки ('1' и '0')
df_train['CLASS'] = df_train['CLASS'].replace({'50000+': 1, '-50000': 0})

# 2. Извлекаем таргет с явным указанием типа и используем to_numpy()
Y = df_train['CLASS'].to_numpy(dtype=np.int64)

# 3. Удаляем колонку
del df_train['CLASS']

Y

/tmp/ipykernel_1426323/251902047.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_train['CLASS'] = df_train['CLASS'].replace({'50000+': 1, '-50000': 0})

array([1, 0, 1, ..., 0, 0, 1], shape=(10000,))

In [ ]:
def dummy_encode_categorical_columns(df, categorical_columns):
    result_df = deepcopy(df)
    for column in categorical_columns:
        result_df = pd.concat([result_df, pd.get_dummies(result_df[column], prefix=column, prefix_sep=': ')], axis=1)
        del result_df[column]
    return result_df

In [ ]:
categorical_columns: Set[str] = set(df_train.columns[df_train.dtypes == 'object'])
df_no_cat: pd.DataFrame = dummy_encode_categorical_columns(df_train, categorical_columns)
X_train: np.ndarray = df_no_cat.values.astype(np.float32)

In [39]:
df_no_cat

,AAGE,ADTIND,ADTOCC,AHRSPAY,CAPGAIN,CAPLOSS,DIVVAL,MARSUPWT,NOEMP,SEOTR,...,PRCITSHP: Native-BornintheUnitedStates,AREORGN: Allother,AREORGN: CentralorSouthAmerican,AREORGN: Chicano,AREORGN: Cuban,AREORGN: Donotknow,AREORGN: Mexican(Mexicano),AREORGN: Mexican-American,AREORGN: OtherSpanish,AREORGN: PuertoRican
0,43,43,10,0,0,0,2,1232.40,6,0,...,True,True,False,False,False,False,False,False,False,False
1,0,0,0,0,0,0,0,3062.92,0,0,...,True,True,False,False,False,False,False,False,False,False
2,44,11,22,0,0,0,1000,1502.40,6,0,...,True,True,False,False,False,False,False,False,False,False
3,43,35,17,0,99999,0,1000,295.30,2,0,...,True,True,False,False,False,False,False,False,False,False
4,39,24,26,0,0,0,0,2700.08,6,0,...,True,True,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,57,42,26,0,0,0,500,2115.52,1,0,...,True,True,False,False,False,False,False,False,False,False
9996,13,0,0,0,0,0,0,1732.77,0,0,...,True,True,False,False,False,False,False,False,False,False
9997,5,0,0,0,0,0,0,2326.47,0,0,...,True,True,False,False,False,False,False,False,False,False
9998,64,0,0,0,0,0,0,3217.88,0,0,...,True,True,False,False,False,False,False,False,False,False
9999,29,45,15,0,0,0,0,1646.68,4,2,...,True,True,False,False,False,False,False,False,False,False

In [40]:
X_train

array([[43., 43., 10., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [44., 11., 22., ...,  0.,  0.,  0.],
       ...,
       [ 5.,  0.,  0., ...,  0.,  0.,  0.],
       [64.,  0.,  0., ...,  0.,  0.,  0.],
       [29., 45., 15., ...,  0.,  0.,  0.]],
      shape=(10000, 367), dtype=float32)

In [41]:
cl=np.random.randint(2, size=10000)
ag=np.random.randint(low=31,high=100, size=10000)
ag

array([91, 84, 79, ..., 84, 88, 51], shape=(10000,))